"use cliente"
import "../globals.css";
import Header from "../components/headerInicio/header";
import Footer from "../components/footer/footer";
import SessionWrapper from "../components/SessionWrapper/SessionWrapper";

export const metadata = {
  title: "Gestión de Gastos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper> 
      <>
      <div className="w-full bg-white shadow-md z-10 fixed top-0">
        <Header/>
        </div>
        {children}
        <div className="flex-grow"></div>
        <footer className="w-full bg-white shadow-md z-10 fixed bottom-0">
          <Footer></Footer>
        </footer>
      </>
    </SessionWrapper>
);
}
