import "../globals.css";
import Sidebar from "../components/menu/sideBar";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import SessionWrapper from "../components/SessionWrapper/SessionWrapper";

export const metadata = {
  title: "Gestión de Gastos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
    <>
      <div className="w-full bg-white shadow-md z-50 fixed top-0">
        <Header/>
      </div>
      <Sidebar/>
      {children}
      <footer className="w-full bg-white shadow-md z-50 fixed bottom-0">
        <Footer></Footer>
      </footer>
    </>
    </SessionWrapper>
);
}
