import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // usa ./ en vez de ../ si estás en /app
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gestión de Gastos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}